from app.domain.entities.loanInstallment import LoanInstallment
from app.domain.entities.typeBankAccount import TypeBankAccount
from app.domain.entities.payrollSinergy import PayrollSinergy
from app.domain.entities.typeWithdrawal import TypeWithdrawal
from app.domain.entities.deductionPlan import DeductionPlan
from app.domain.entities.descTsueldo import DescTsueldo
from app.domain.entities.absenteeism import Absenteeism
from app.domain.entities.loanStatus import LoanStatus
from app.domain.entities.incapacity import Incapacity
from app.domain.entities.diagnosis import Diagnosis
from app.infrastructure.db.connection import Base
from app.domain.entities.descCen1 import DescCen1
from app.domain.entities.descCen2 import DescCen2
from app.domain.entities.descCen3 import DescCen3
from app.domain.entities.descCen4 import DescCen4
from app.domain.entities.loanLog import LoanLog
from app.domain.entities.bank import Bank
from app.domain.entities.loan import Loan