name: sighacalco-prod

services:
  authentication:
    container_name: sighacalco_prod_authentication
    build:
      context: ./sighaCalco.Authentication
      dockerfile: Dockerfile
    env_file:
      - ./sighaCalco.Authentication/.env.prod
    ports:
      - "8201:8000"
    restart: unless-stopped

  loans:
    container_name: sighacalco_prod_loans
    build:
      context: ./sighaCalco.Loans
      dockerfile: Dockerfile
    env_file:
      - ./sighaCalco.Loans/.env.prod
    ports:
      - "8202:8000"
    restart: unless-stopped

  integration:
    container_name: sighacalco_prod_integration
    build:
      context: ./sighaCalco.Integration
      dockerfile: Dockerfile
    env_file:
      - ./sighaCalco.Integration/.env.prod
    ports:
      - "8203:8000"
    volumes:
      - ./sighaCalco.Integration/generated:/app/generated
    restart: unless-stopped