services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    container_name: sighacalco_onlyoffice_documentserver
    restart: unless-stopped
    ports:
      - "8085:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - JWT_HEADER=Authorization
    volumes:
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/lib:/var/lib/onlyoffice